import Head from "next/head";
import { GetStaticProps } from "next";
import { serverSideTranslations } from "next-i18next/serverSideTranslations";
import Page from "../src/ui/pages/home";

export default function HomePage() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Page />
    </div>
  );
}

export const getStaticProps: GetStaticProps = async ({ locale }) => {
  const initialLocale = locale || "es";

  return {
    props: {
      ...(await serverSideTranslations(initialLocale, [
        "home",
        "projects",
        "goals",
        "contributions",
        "navbar",
        "auth",
      ])),
    },
  };
};
